import { Toaster } from "react-hot-toast";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { ReduxProvider } from "./redux-provider";
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Super > Dashboard | Itsoftworld",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat?.className}>
        <Toaster position="bottom-center" />
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
